Repository DeveloperAcademy-POSTECH/MacC-Team-DGC, pull requests merged in 2023-10, with the labels that each got.

#20 [Feat] 내 정보 화면 상단 뷰 레이아웃 및 기능 구현
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Assets.xcassets/Profile.imageset/Contents.json
  Carmunication/Assets.xcassets/Profile.imageset/DefaultProfile.png
  Carmunication/Assets.xcassets/cameraBtn.imageset/Contents.json
  Carmunication/Assets.xcassets/cameraBtn.imageset/cameraBtn.png
  Carmunication/Controllers/MyPage/InquiryViewController.swift
  Carmunication/Controllers/MyPage/MyPageViewController.swift
  Carmunication/Controllers/MyPage/PrivacyViewController.swift
  Carmunication/Controllers/MyPage/SettingsViewController.swift
Labels: Feat, Design

#22 [feat] 카풀시 실시간 위치 정보 확인을 위한 네이버 지도 세팅
  .gitignore
  Carmunication.xcodeproj/project.pbxproj
  Carmunication.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Carmunication/AppDelegate.swift
  Carmunication/Controllers/SessionStart/SessionMapViewController.swift
  Carmunication/Extensions/Bundle+Extension.swift
  Carmunication/Info.plist
Labels: Feat

#24 [Feat] 메인 그룹 리스트 화면 생성
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Assets.xcassets/SessionListImage/Contents.json
  Carmunication/Assets.xcassets/SessionListImage/ImCaptainButton.imageset/Contents.json
  Carmunication/Assets.xcassets/SessionListImage/ImCaptainButton.imageset/UserIdentity.png
  Carmunication/Assets.xcassets/SessionListImage/ImCrewButton.imageset/Contents.json
  Carmunication/Assets.xcassets/SessionListImage/ImCrewButton.imageset/UserIdentity2.png
  Carmunication/Assets.xcassets/SessionListImage/crewImageDefalut.imageset/Contents.json
  Carmunication/Assets.xcassets/SessionListImage/crewImageDefalut.imageset/ProfileSize.png
  Carmunication/Assets.xcassets/SessionListImage/elipse.imageset/Contents.json
  Carmunication/Assets.xcassets/SessionListImage/elipse.imageset/elipse.png
  Carmunication/Controllers/SessionList/CustomListTableViewCell.swift
  Carmunication/Controllers/SessionList/GroupAddTableViewCell.swift
  Carmunication/Controllers/SessionList/GroupAddViewController.swift
  Carmunication/Controllers/SessionList/GroupDetailViewController.swift
  Carmunication/Controllers/SessionList/NotFoundCrewTableViewCell.swift
  Carmunication/Controllers/SessionList/SelectPointMapViewController.swift
  Carmunication/Controllers/SessionListViewController.swift
  Carmunication/Extensions/UIFont+Extension.swift
  Carmunication/Extensions/UIImage+Extension.swift
  Carmunication/Models/Color/SemanticColor.swift
  Carmunication/Models/DummyGroup/DummyGroup.swift
  Carmunication/Models/Font/CarmuFont.swift
Labels: Feat

#26 [Feat] 유저 로그인 정보에 따른 처리 및 저장
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/LoginViewController.swift
  Carmunication/Controllers/MyPage/MyPageViewController.swift
  Carmunication/Controllers/MyPage/SettingsViewController.swift
  Carmunication/Models/KeychainItem.swift
  Carmunication/SceneDelegate.swift
Labels: Feat

#29 [Feat] 크루 리스트 상세 페이지 구현
  Carmunication.xcodeproj/project.pbxproj
  Carmunication.xcodeproj/project.xcworkspace/xcuserdata/donghyeon.xcuserdatad/UserInterfaceState.xcuserstate
  Carmunication.xcodeproj/xcuserdata/donghyeon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Carmunication.xcodeproj/xcuserdata/donghyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  Carmunication/Assets.xcassets/SessionListImage/StopPoint.imageset/Contents.json
  Carmunication/Assets.xcassets/SessionListImage/StopPoint.imageset/StopPoint.png
  Carmunication/Controllers/SessionList/CustomListTableViewCell.swift
  Carmunication/Controllers/SessionList/GradientLineView.swift
  Carmunication/Controllers/SessionList/GroupAddTableViewCell.swift
  Carmunication/Controllers/SessionList/GroupAddViewController.swift
  Carmunication/Controllers/SessionList/GroupDetailTableViewCell.swift
  Carmunication/Controllers/SessionList/GroupDetailViewController.swift
  Carmunication/Controllers/SessionList/NotFoundCrewTableViewCell.swift
  Carmunication/Controllers/SessionList/SelectPointMapViewController.swift
  Carmunication/Controllers/SessionListViewController.swift
  Carmunication/Extensions/UIColor+Extension.swift
  Carmunication/Models/DummyGroup/DummyGroup.swift
  Carmunication/Models/Font/CarmuFont.swift
Labels: Feat, Design, Chore

#34 [Chore] PR 요청시 SwiftLint 동작하도록 환경 세팅
  .github/workflows/swiftlint.yml
  .swiftlint.yml
Labels: Chore

#35 [Feat] 내 정보, 설정 화면 뷰 구성 작업
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Assets.xcassets/appLogo.imageset/Contents.json
  Carmunication/Assets.xcassets/appLogo.imageset/appLogo.png
  Carmunication/Assets.xcassets/profile.imageset/Contents.json
  Carmunication/Assets.xcassets/profile.imageset/profile.png
  Carmunication/Controllers/LoginViewController.swift
  Carmunication/Controllers/MyPage/InquiryViewController.swift
  Carmunication/Controllers/MyPage/MyPageViewController.swift
  Carmunication/Controllers/MyPage/PrivacyViewController.swift
  Carmunication/Controllers/MyPage/SettingsViewController.swift
  Carmunication/Extensions/UIImage+Extension.swift
  Carmunication/Views/LoginView.swift
  Carmunication/Views/MyPage/InquiryView.swift
  Carmunication/Views/MyPage/MyPageView.swift
  Carmunication/Views/MyPage/PrivacyView.swift
  Carmunication/Views/MyPage/SettingsView.swift
Labels: Feat, Design

#36 Bazzi/feat/#31
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Assets.xcassets/SessionListImage/AddViewSidebarDot.imageset/AddViewSidebarDot.png
  Carmunication/Assets.xcassets/SessionListImage/AddViewSidebarDot.imageset/Contents.json
  Carmunication/Assets.xcassets/SessionListImage/stopoverRemove.imageset/Contents.json
  Carmunication/Assets.xcassets/SessionListImage/stopoverRemove.imageset/stopoverRemove.png
  Carmunication/Assets.xcassets/SessionListImage/unknownCrew.imageset/Contents.json
  Carmunication/Assets.xcassets/SessionListImage/unknownCrew.imageset/unknownCrew.png
  Carmunication/Controllers/SessionList/GroupAddViewController.swift
  Carmunication/Controllers/SessionList/SelectBoardingCrewModalViewController.swift
  Carmunication/Controllers/SessionList/SessionListViewController.swift
  Carmunication/Controllers/SessionList/StartTimeSelectViewController.swift
  Carmunication/Models/Color/SemanticColor.swift
  Carmunication/Views/SessionList/Common/GradientLineView.swift
  Carmunication/Views/SessionList/GroupAdd/GroupAddModalCollectionViewCell.swift
  Carmunication/Views/SessionList/GroupAdd/GroupAddTableViewCell.swift
  Carmunication/Views/SessionList/GroupAdd/GroupAddView.swift
  Carmunication/Views/SessionList/GroupAdd/SelectBoardingCrewModalView.swift
  Carmunication/Views/SessionList/GroupAdd/StartTimeSelectView.swift
  Carmunication/Views/SessionList/GroupDetail/GroupDetailTableViewCell.swift
  Carmunication/Views/SessionList/GroupDetail/GroupDetailView.swift
  Carmunication/Views/SessionList/SessionList/CustomListTableViewCell.swift
  Carmunication/Views/SessionList/SessionList/NotFoundCrewTableViewCell.swift
  Carmunication/Views/SessionList/SessionList/SessionListView.swift
Labels: Feat, Design

#37 [Feat] 메인 화면 구성하기
  Carmunication.xcodeproj/project.pbxproj
  Carmunication.xcodeproj/xcshareddata/xcschemes/Carmunication.xcscheme
  Carmunication/Controllers/SessionStart/SessionStartViewController.swift
  Carmunication/Extensions/Date+Extension.swift
  Carmunication/Extensions/SessionStartView+Extension.swift
  Carmunication/Models/GroupData.swift
  Carmunication/Views/SessionStart/SessionStartView.swift
Labels: Feat

#43 [Refactor] SessionStartView 리팩토링
  Carmunication/Extensions/SessionStartView+Extension.swift
  Carmunication/Views/SessionStart/SessionStartView.swift
Labels: Refactor

#45 [Feat] 통합 user, group, session 데이터 모델 생성
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Models/DummyData/Crew.swift
  Carmunication/Models/DummyData/DummyData.swift
  Carmunication/Models/DummyData/DummyGroup.swift
  Carmunication/Models/DummyData/Friendship.swift
  Carmunication/Models/DummyData/Group.swift
  Carmunication/Models/DummyData/Point.swift
  Carmunication/Models/DummyData/Session.swift
  Carmunication/Models/DummyData/User.swift
Labels: Feat

#46 [Feat] SessionStartView 디자인 변경
  Carmunication/Controllers/SessionStart/SessionStartViewController.swift
  Carmunication/Extensions/SessionStartView+Extension.swift
  Carmunication/Models/DummyData/Friendship.swift
  Carmunication/Models/DummyData/User.swift
  Carmunication/Models/GroupData.swift
  Carmunication/Views/SessionStart/SessionStartView.swift
Labels: Feat

#50 [Feat] Session Group Data 형식 확인
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/SessionStart/SessionStartViewController.swift
  Carmunication/Models/DummyData/Group.swift
  Carmunication/Models/DummyData/Point.swift
  Carmunication/Models/GroupData.swift
  Carmunication/Views/SessionStart/GroupCollectionViewCell.swift
Labels: Feat

#51 [Feat] 크루 리스트 화면 버튼 액션 추가
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/SessionList/GroupAddViewController.swift
  Carmunication/Controllers/SessionList/GroupDetailViewController.swift
  Carmunication/Controllers/SessionList/SelectBoardingCrewModalViewController.swift
  Carmunication/Controllers/SessionList/SelectStartTimeViewController.swift
  Carmunication/Views/SessionList/GroupAdd/SelectBoardingCrewModalView.swift
  Carmunication/Views/SessionList/GroupAdd/SelectStartTimeModalView.swift
  Carmunication/Views/SessionList/GroupDetail/GroupDetailView.swift
Labels: Feat

#52 [Feat] 애플 로그인, 회원탈퇴시 DB 갱신
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/LoginViewController.swift
  Carmunication/Controllers/MyPage/SettingsViewController.swift
  Carmunication/Models/DummyData/DummyData.swift
  Carmunication/Models/DummyData/User.swift
Labels: Feat

#57 [refactor] #56 - uid 파이어베이스가 아닌 키체인을 사용하도록 변경
  Carmunication/Controllers/LoginViewController.swift
  Carmunication/Controllers/MyPage/SettingsViewController.swift
  Carmunication/Models/DummyData/User.swift
  Carmunication/Models/KeychainItem.swift
Labels: Refactor

#63 [Design] SessionStartView 디자인
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Assets.xcassets/defaultStoryImage.imageset/Contents.json
  Carmunication/Assets.xcassets/defaultStoryImage.imageset/defaultStoryImage.png
  Carmunication/Controllers/SessionStart/SessionStartViewController.swift
  Carmunication/Extensions/SessionStartView+Extension.swift
  Carmunication/Models/DummyData/Group.swift
  Carmunication/Views/SessionStart/GroupCollectionViewCell.swift
  Carmunication/Views/SessionStart/SessionStartMidView.swift
  Carmunication/Views/SessionStart/SessionStartView.swift
Labels: Feat, Design, Refactor

#65 [Feat] 유저 닉네임 수정 구현 & 회원탈퇴 로직 수정
  Carmunication/Controllers/LoginViewController.swift
  Carmunication/Controllers/MyPage/MyPageViewController.swift
  Carmunication/Controllers/MyPage/SettingsViewController.swift
  Carmunication/Models/DummyData/User.swift
  Carmunication/Models/KeychainItem.swift
  Carmunication/Views/MyPage/MyPageView.swift
Labels: Fix, Feat

#66 [Feat] MapKit으로 주소 검색 기능으로 상세주소, 좌표, 건물명 불러오는 기능 구현
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/SessionList/SelectAddressViewController.swift
  Carmunication/Models/GroupAdd/SelectAddressModel.swift
  Carmunication/Views/SessionList/GroupAdd/DefaultAddressTableViewCell.swift
Labels: Feat

#68 [Refactor] SessionStartMidView에 컴포넌트 추가
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/SessionStart/SessionStartViewController.swift
  Carmunication/Extensions/SessionStartView+Extension.swift
  Carmunication/Models/DummyData/Group.swift
  Carmunication/Views/SessionStart/SessionStartMidView.swift
  Carmunication/Views/SessionStart/SessionStartView.swift
Labels: Feat, Design, Refactor

#70 [Feat] 프로필 사진 설정 DB 반영
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/MyPage/MyPageViewController.swift
  Carmunication/Models/DummyData/User.swift
Labels: Feat

#75 [Feat] 상세 뷰로 이동하는 액션 구현
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Assets.xcassets/DetailPointMap/CenterMarker.imageset/CenterMarker.png
  Carmunication/Assets.xcassets/DetailPointMap/CenterMarker.imageset/Contents.json
  Carmunication/Assets.xcassets/DetailPointMap/Contents.json
  Carmunication/Controllers/SessionList/GroupAdd/GroupAddViewController.swift
  Carmunication/Controllers/SessionList/GroupAdd/SelectAddressViewController.swift
  Carmunication/Controllers/SessionList/GroupAdd/SelectBoardingCrewModalViewController.swift
  Carmunication/Controllers/SessionList/GroupAdd/SelectDetailPointMapViewController.swift
  Carmunication/Controllers/SessionList/GroupAdd/SelectStartTimeViewController.swift
  Carmunication/Controllers/SessionList/GroupDetail/GroupDetailViewController.swift
  Carmunication/Controllers/SessionList/SessionListMain/SessionListViewController.swift
  Carmunication/Models/GroupAdd/SelectAddressModel.swift
  Carmunication/Views/SessionList/Cell/DefaultAddressTableViewCell.swift
  Carmunication/Views/SessionList/Cell/GroupAddModalCollectionViewCell.swift
  Carmunication/Views/SessionList/Cell/GroupAddTableViewCell.swift
  Carmunication/Views/SessionList/Cell/SelectAddressTableViewCell.swift
  Carmunication/Views/SessionList/GroupAdd/SelectAddressView.swift
  Carmunication/Views/SessionList/GroupAdd/SelectDetailPointMapView.swift
  Carmunication/Views/SessionList/GroupDetail/Cell/GroupDetailTableViewCell.swift
  Carmunication/Views/SessionList/SessionListMain/Cell/CustomListTableViewCell.swift
  Carmunication/Views/SessionList/SessionListMain/Cell/NotFoundCrewTableViewCell.swift
  Carmunication/Views/SessionList/SessionListMain/SessionListView.swift
Labels: Feat

#80 [Feat] 이전 화면, 다음화면 간 데이터 전달 구현
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/SessionList/GroupAdd/GroupAddViewController.swift
  Carmunication/Controllers/SessionList/GroupAdd/SelectAddressViewController.swift
  Carmunication/Controllers/SessionList/GroupAdd/SelectDetailPointMapViewController.swift
  Carmunication/Controllers/SessionList/GroupAdd/SelectStartTimeViewController.swift
  Carmunication/Extensions/Date+Extension.swift
  Carmunication/Extensions/String+Extension.swift
  Carmunication/Models/DummyData/Point2.swift
  Carmunication/Views/SessionList/Cell/GroupAddTableViewCell.swift
  Carmunication/Views/SessionList/GroupAdd/SelectStartTimeModalView.swift
Labels: Feat, Design, Del, Chore

#81 [Design] SessionStartView 데이터 없을 때의 화면 생성 및 동승자 화면 구성
  Carmunication/Controllers/SessionStart/SessionStartViewController.swift
  Carmunication/Models/DummyData/Group.swift
  Carmunication/Views/SessionStart/SessionStartView.swift
Labels: Feat, Design

#82 [Feat] 친구 추가 기능 구현
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/LoginViewController.swift
  Carmunication/Controllers/MyPage/FriendAddViewController.swift
  Carmunication/Controllers/MyPage/FriendDetailViewController.swift
  Carmunication/Controllers/MyPage/FriendListViewController.swift
  Carmunication/Controllers/MyPage/MyPageViewController.swift
  Carmunication/Models/DummyData/DummyData.swift
  Carmunication/Models/DummyData/Friendship.swift
  Carmunication/Models/DummyData/User.swift
  Carmunication/Views/MyPage/FriendAddView.swift
  Carmunication/Views/MyPage/FriendDetailView.swift
  Carmunication/Views/MyPage/FriendListTableViewCell.swift
  Carmunication/Views/MyPage/MyPageView.swift
  Carmunication/Views/MyPage/NoSearchedResultTableViewCell.swift
Labels: Fix, Feat

#87 [Feat] User에 디바이스 토큰값 추가
  .gitignore
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/AppDelegate.swift
  Carmunication/Carmunication.entitlements
  Carmunication/Controllers/LoginViewController.swift
  Carmunication/Controllers/MainTabBarViewController.swift
  Carmunication/Controllers/MyPage/FriendAddViewController.swift
  Carmunication/Controllers/MyPage/FriendListViewController.swift
  Carmunication/Info.plist
  Carmunication/Models/DummyData/DummyData.swift
  Carmunication/Models/DummyData/User.swift
Labels: Feat

#89 [Design] 친구 없을 때 친구관리 화면 구성
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/MyPage/FriendListViewController.swift
  Carmunication/Views/MyPage/FriendListView.swift
Labels: Feat, Design

#90 [Fix] User 모델 필수 프로퍼티 옵셔널 타입으로 변경
  Carmunication/Controllers/LoginViewController.swift
  Carmunication/Controllers/MyPage/FriendAddViewController.swift
  Carmunication/Controllers/MyPage/FriendListViewController.swift
  Carmunication/Controllers/MyPage/MyPageViewController.swift
  Carmunication/Models/DummyData/User.swift
Labels: Fix, Add

#91 [Design] 그룹이 없을 떄 나타나는 화면 디자인
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/SessionStart/SessionStartViewController.swift
  Carmunication/Views/SessionStart/SessionStartMidNoGroupView.swift
Labels: Design

#92 [Feat] 운전자가 버튼 클릭으로 맵뷰까지 이동하는 로직 생성
  Carmunication/Controllers/SessionStart/SessionStartViewController.swift
Labels: Feat, Design

#94 [Chore] PR 피드백 기반 수정
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/SessionList/GroupAdd/GroupAddViewController.swift
  Carmunication/Controllers/SessionStart/ModalQueueViewController.swift
  Carmunication/Controllers/SessionStart/SessionStartViewController.swift
  Carmunication/Models/DummyData/Group.swift
  Carmunication/Models/DummyData/Point.swift
  Carmunication/Models/DummyData/Point2.swift
  Carmunication/Views/SessionStart/ModalQueueView.swift
  Carmunication/Views/SessionStart/SessionStartMidNoGroupView.swift
  Carmunication/Views/SessionStart/SessionStartMidView.swift
  Carmunication/Views/SessionStart/SessionStartView.swift
Labels: Chore

#101 [Feat] 맵뷰 출발지, 경유지, 도착지 표시 및 경로 표시
  Carmunication/Assets.xcassets/mapView/Contents.json
  Carmunication/Assets.xcassets/mapView/destination.imageset/Contents.json
  Carmunication/Assets.xcassets/mapView/destination.imageset/destination.png
  Carmunication/Assets.xcassets/mapView/mapViewBackButton.imageset/Contents.json
  Carmunication/Assets.xcassets/mapView/mapViewBackButton.imageset/mapViewBackButton.png
  Carmunication/Assets.xcassets/mapView/pickupLocation1.imageset/Contents.json
  Carmunication/Assets.xcassets/mapView/pickupLocation1.imageset/pickupLocation1.png
  Carmunication/Assets.xcassets/mapView/pickupLocation2.imageset/Contents.json
  Carmunication/Assets.xcassets/mapView/pickupLocation2.imageset/pickupLocation2.png
  Carmunication/Assets.xcassets/mapView/pickupLocation3.imageset/Contents.json
  Carmunication/Assets.xcassets/mapView/pickupLocation3.imageset/pickupLocation3.png
  Carmunication/Assets.xcassets/mapView/startingPoint.imageset/Contents.json
  Carmunication/Assets.xcassets/mapView/startingPoint.imageset/startingPoint.png
  Carmunication/Controllers/SessionStart/SessionMapViewController.swift
  Carmunication/Extensions/Bundle+Extension.swift
Labels: Feat, Design

#100 [Feat] 탑승 크루 설정 모달 데이터 표시, 전달 구현
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Assets.xcassets/CrewPlusImage.imageset/Contents.json
  Carmunication/Assets.xcassets/CrewPlusImage.imageset/CrewPlusImage.png
  Carmunication/Controllers/SessionList/GroupAdd/GroupAddViewController+Extension.swift
  Carmunication/Controllers/SessionList/GroupAdd/GroupAddViewController.swift
  Carmunication/Controllers/SessionList/GroupAdd/SelectBoardingCrewModalViewController.swift
  Carmunication/Utils/FirebaseManager.swift
  Carmunication/Views/SessionList/Cell/CrewImageButton.swift
  Carmunication/Views/SessionList/Cell/GroupAddTableViewCell.swift
  Carmunication/Views/SessionList/GroupAdd/SelectBoardingCrewModalView.swift
Labels: Feat

#104 [Feat] 서버 푸시 알림 생성하기
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/SessionStart/SessionStartViewController.swift
Labels: Feat

#109 [Feat] 크루 만들기 상세 기능 최종 구현
  Carmunication/Controllers/SessionList/GroupAdd/GroupAddViewController.swift
Labels: Feat

#114 [Chore] PR시 수정분에 대해서만 린트 확인하도록 수정
  .github/workflows/swiftlint.yml
Labels: Chore

#116 [Refactor] 경고 없애기 및 사용성 개선 작업
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/AppDelegate.swift
  Carmu/Sources/Controllers/LoginViewController.swift
  Carmu/Sources/Controllers/MainTabBarViewController.swift
  Carmu/Sources/Controllers/MyPage/FriendAddViewController.swift
  Carmu/Sources/Controllers/MyPage/SettingsViewController.swift
  Carmu/Sources/Models/KeychainItem.swift
  Carmu/Sources/Views/MyPage/FriendAddView.swift
  Carmu/Sources/Views/MyPage/FriendDetailView.swift
  Carmu/Sources/Views/MyPage/FriendListTableViewCell.swift
  Carmu/Sources/Views/MyPage/InquiryView.swift
  Carmu/Sources/Views/MyPage/MyPageView.swift
  Carmu/Sources/Views/MyPage/PrivacyView.swift
  Carmu/Sources/Views/MyPage/SettingsView.swift
Labels: Feat, Refactor

#117 [Feat] ERD 수정
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DummyData/Group.swift
  Carmu/Sources/Models/DummyData/Point.swift
  Carmu/Sources/Models/DummyData/Session.swift
  Carmu/Sources/Models/DummyData/User.swift
  Carmu/Sources/Views/SessionStart/SessionStartMidView.swift
Labels: Feat

#120 [Settings] 배포에 필요한 설정
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/AppIcon.appiconset/100.png
  Carmu/Assets.xcassets/AppIcon.appiconset/1024.png
  Carmu/Assets.xcassets/AppIcon.appiconset/114.png
  Carmu/Assets.xcassets/AppIcon.appiconset/120.png
  Carmu/Assets.xcassets/AppIcon.appiconset/128.png
  Carmu/Assets.xcassets/AppIcon.appiconset/144.png
  Carmu/Assets.xcassets/AppIcon.appiconset/152.png
  Carmu/Assets.xcassets/AppIcon.appiconset/16.png
  Carmu/Assets.xcassets/AppIcon.appiconset/167.png
  Carmu/Assets.xcassets/AppIcon.appiconset/172.png
  Carmu/Assets.xcassets/AppIcon.appiconset/180.png
  Carmu/Assets.xcassets/AppIcon.appiconset/196.png
  Carmu/Assets.xcassets/AppIcon.appiconset/20.png
  Carmu/Assets.xcassets/AppIcon.appiconset/216.png
  Carmu/Assets.xcassets/AppIcon.appiconset/256.png
  Carmu/Assets.xcassets/AppIcon.appiconset/29.png
  Carmu/Assets.xcassets/AppIcon.appiconset/32.png
  Carmu/Assets.xcassets/AppIcon.appiconset/40.png
  Carmu/Assets.xcassets/AppIcon.appiconset/48.png
  Carmu/Assets.xcassets/AppIcon.appiconset/50.png
  Carmu/Assets.xcassets/AppIcon.appiconset/512.png
  Carmu/Assets.xcassets/AppIcon.appiconset/55.png
  Carmu/Assets.xcassets/AppIcon.appiconset/57.png
  Carmu/Assets.xcassets/AppIcon.appiconset/58.png
  Carmu/Assets.xcassets/AppIcon.appiconset/60.png
  Carmu/Assets.xcassets/AppIcon.appiconset/64.png
  Carmu/Assets.xcassets/AppIcon.appiconset/66.png
  Carmu/Assets.xcassets/AppIcon.appiconset/72.png
  Carmu/Assets.xcassets/AppIcon.appiconset/76.png
  Carmu/Assets.xcassets/AppIcon.appiconset/80.png
  Carmu/Assets.xcassets/AppIcon.appiconset/87.png
  Carmu/Assets.xcassets/AppIcon.appiconset/88.png
  Carmu/Assets.xcassets/AppIcon.appiconset/92.png
  Carmu/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Setting

#121 [Feat] 친구 추가되었을 시 친구에게 서버 푸시
  Carmu/Sources/Controllers/MyPage/FriendAddViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
Labels: Feat, Refactor

#125 [Feat] 맵뷰 하단에 상세 뷰 그리기
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/SessionStart/SessionMapViewController.swift
  Carmu/Sources/Models/Color/SemanticColor.swift
  Carmu/Sources/Utils/PaddingLabel.swift
  Carmu/Sources/Views/SessionStart/SessionMapView/SessionMapDetailView.swift
  Carmu/Sources/Views/SessionStart/SessionMapView/TimeDataView.swift
Labels: Design

#127 [Feat] 그룹 추가 시 Firebase에 데이터 Create Feat
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/SessionList/GroupAdd/GroupAddViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DummyData/Crew.swift
  Carmu/Sources/Models/DummyData/DummyData.swift
  Carmu/Sources/Models/DummyData/Group.swift
  Carmu/Sources/Models/DummyData/Point.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Feat, Chore

#131 [Feat] SessionStartView에 Group 데이터 연동
  Carmu/Assets.xcassets/profile.imageset/profile.png
  Carmu/Sources/Controllers/MyPage/FriendAddViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DummyData/Group.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/SessionStart/GroupCollectionViewCell.swift
  Carmu/Sources/Views/SessionStart/SessionStartView.swift
Labels: Feat

#133 [chore] #132 - 이미지 추가 및 적용
  Carmu/Assets.xcassets/blinker.imageset/Contents.json
  Carmu/Assets.xcassets/blinker.imageset/신호등.png
  Carmu/Sources/Views/SessionStart/SessionStartMidNoGroupView.swift
Labels: Chore

#134 [Feat] MapView 인터랙션 구현
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/mapView/quitCarpoolButton.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/quitCarpoolButton.imageset/quitCarpoolButton.png
  Carmu/Sources/Controllers/SessionStart/SessionMapView/NoticeLateViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionMapView/SessionMapViewController.swift
  Carmu/Sources/Models/PickupLocation.swift
  Carmu/Sources/Views/SessionStart/SessionMapView/NoticeLateView.swift
  Carmu/Sources/Views/SessionStart/SessionMapView/SessionMapDetailView.swift
Labels: Feat, Design

#137 [Feat] 지각 버튼 클릭 시 알림 보내기
  Carmu/Sources/Controllers/SessionStart/SessionMapView/NoticeLateViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
Labels: Feat, Chore

#139 [Feat] 지각 메세지 보냈을 시 토스트 알림 보내기
  Carmu/Sources/Controllers/SessionStart/SessionMapView/NoticeLateViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionMapView/SessionMapViewController.swift
  Carmu/Sources/Views/SessionStart/SessionStartMidView.swift
Labels: Feat
