Repository DeveloperAcademy-POSTECH/MacC-Team-DGC, pull requests merged in 2023-11, with the labels that each got.

#148 [Feat] 여정화면에서 탭바 삭제
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/LoginViewController.swift
  Carmu/Sources/Controllers/MainTabBarViewController.swift
  Carmu/Sources/Controllers/SessionList/GroupAdd/GroupAddViewController.swift
  Carmu/Sources/Controllers/SessionList/GroupAdd/SelectAddressViewController.swift
  Carmu/Sources/Controllers/SessionList/GroupAdd/SelectBoardingCrewModalViewController.swift
  Carmu/Sources/Controllers/SessionList/GroupAdd/SelectDetailPointMapViewController.swift
  Carmu/Sources/Controllers/SessionList/GroupAdd/SelectStartTimeViewController.swift
  Carmu/Sources/Controllers/SessionList/GroupDetail/GroupDetailViewController.swift
  Carmu/Sources/Controllers/SessionList/SessionListMain/SessionListViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Views/SessionList/Cell/CrewImageButton.swift
  Carmu/Sources/Views/SessionList/Cell/DefaultAddressTableViewCell.swift
  Carmu/Sources/Views/SessionList/Cell/GroupAddModalCollectionViewCell.swift
  Carmu/Sources/Views/SessionList/Cell/GroupAddTableViewCell.swift
  Carmu/Sources/Views/SessionList/Cell/SelectAddressTableViewCell.swift
  Carmu/Sources/Views/SessionList/Common/GradientLineView.swift
  Carmu/Sources/Views/SessionList/GroupAdd/GroupAddView.swift
  Carmu/Sources/Views/SessionList/GroupAdd/SelectAddressView.swift
  Carmu/Sources/Views/SessionList/GroupAdd/SelectBoardingCrewModalView.swift
  Carmu/Sources/Views/SessionList/GroupAdd/SelectDetailPointMapView.swift
  Carmu/Sources/Views/SessionList/GroupAdd/SelectStartTimeModalView.swift
  Carmu/Sources/Views/SessionList/GroupDetail/Cell/GroupDetailTableViewCell.swift
  Carmu/Sources/Views/SessionList/GroupDetail/GroupDetailView.swift
  Carmu/Sources/Views/SessionList/SessionListMain/Cell/CustomListTableViewCell.swift
  Carmu/Sources/Views/SessionList/SessionListMain/Cell/NotFoundCrewTableViewCell.swift
  Carmu/Sources/Views/SessionList/SessionListMain/SessionListView.swift
Labels: Feat

#147 [Refactor] 서버 푸시 관련 코드 수정
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
Labels: Feat, Refactor

#159 [Feat] 크루 생성 - 포지션 설정 화면 구현
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/PositionSelect/Contents.json
  Carmu/Assets.xcassets/PositionSelect/PositionSelectCrew.imageset/Contents.json
  Carmu/Assets.xcassets/PositionSelect/PositionSelectCrew.imageset/PositionSelectCrew.png
  Carmu/Assets.xcassets/PositionSelect/PositionSelectDriver.imageset/Contents.json
  Carmu/Assets.xcassets/PositionSelect/PositionSelectDriver.imageset/PositionSelectDriver.png
  Carmu/Sources/Controllers/CrewMake/PositionSelectViewController.swift
  Carmu/Sources/Utils/CrewMakeUtil.swift
  Carmu/Sources/Utils/LargeSelectButton.swift
  Carmu/Sources/Views/CrewMake/PositionSelectView.swift
Labels: Feat, Design

#160 [Refactor] 파이어베이스 DB 접근 메서드 FirebaseManager로 이동
  Carmu/Sources/Controllers/LoginViewController.swift
  Carmu/Sources/Controllers/MyPage/FriendAddViewController.swift
  Carmu/Sources/Controllers/MyPage/FriendDetailViewController.swift
  Carmu/Sources/Controllers/MyPage/FriendListViewController.swift
  Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
  Carmu/Sources/Controllers/MyPage/SettingsViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Refactor

#161 [Feat] 크루 생성 - 공유 초대코드 입력 화면 구현(동승자)
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/InviteCodeInputViewController.swift
  Carmu/Sources/Extensions/UIImage+Extension.swift
  Carmu/Sources/Models/Color/SemanticColor.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Views/CrewMake/InviteCodeInputView.swift
  Carmu/Sources/Views/CrewMake/PositionSelectView.swift
Labels: Feat, Design

#162 [Chore] 불필요한 Model 및 프로퍼티 삭제
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DTO/Friendship.swift
  Carmu/Sources/Models/DTO/Group.swift
  Carmu/Sources/Models/DTO/User.swift
  Carmu/Sources/Models/DummyData/DummyData.swift
  Carmu/Sources/Models/DummyData/DummyGroup.swift
  Carmu/Sources/Models/DummyData/Group.swift
  Carmu/Sources/Models/DummyData/Point.swift
  Carmu/Sources/Models/DummyData/Session.swift
  Carmu/Sources/Models/GroupAdd/SelectAddressModel.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/SessionStart/GroupCollectionViewCell.swift
  Carmu/Sources/Views/SessionStart/SessionStartMidView.swift
Labels: Chore, Refactor

#165 [Feat] 크루 생성 - 탑승지 설정 화면 구현(동승자)
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/BoardingPointSelectViewController.swift
  Carmu/Sources/Models/Color/SemanticColor.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Utils/CrewMakeUtil.swift
  Carmu/Sources/Utils/LargeSelectButton.swift
  Carmu/Sources/Utils/StopoverSelectButton.swift
  Carmu/Sources/Views/CrewMake/BoardingPointSelectView.swift
Labels: Feat, Design

#167 [Feat] 크루 생성 - 경유지 유무 선택 화면 구현(운전자)
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/StopoverPointCheck/Contents.json
  Carmu/Assets.xcassets/StopoverPointCheck/NoStopoverPoint.imageset/Contents.json
  Carmu/Assets.xcassets/StopoverPointCheck/NoStopoverPoint.imageset/NoStopoverPoint.png
  Carmu/Assets.xcassets/StopoverPointCheck/YesStopoverPoint.imageset/Contents.json
  Carmu/Assets.xcassets/StopoverPointCheck/YesStopoverPoint.imageset/YesStopoverPoint.png
  Carmu/Sources/Controllers/CrewMake/StopoverPointCheckViewController.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Views/CrewMake/StopoverPointCheckView.swift
Labels: Feat, Design

#166 [Design] 그룹이 없을 때 메인화면 디자인
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/SessionStartView/Contents.json
  Carmu/Assets.xcassets/SessionStartView/DriverBlinker.imageset/Contents.json
  Carmu/Assets.xcassets/SessionStartView/DriverBlinker.imageset/DriverBlinker.png
  Carmu/Assets.xcassets/SessionStartView/NoGroupBlinker.imageset/Contents.json
  Carmu/Assets.xcassets/SessionStartView/NoGroupBlinker.imageset/NoGroupBlinker.png
  Carmu/Assets.xcassets/SessionStartView/PassengerBlinker.imageset/Contents.json
  Carmu/Assets.xcassets/SessionStartView/PassengerBlinker.imageset/PassengerBlinker.png
  Carmu/Assets.xcassets/SessionStartView/myPageButton.imageset/Contents.json
  Carmu/Assets.xcassets/SessionStartView/myPageButton.imageset/myPageButton.png
  Carmu/Assets.xcassets/defaultStoryImage.imageset/defaultStoryImage.png
  Carmu/Assets.xcassets/profile.imageset/profile.png
  Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Extensions/UIImage+Extension.swift
  Carmu/Sources/Models/Color/SemanticColor.swift
  Carmu/Sources/Models/DummyData/Group.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Views/CrewMake/InviteCodeInputView.swift
  Carmu/Sources/Views/MyPage/MyPageView.swift
  Carmu/Sources/Views/SessionStart/SessionStartMidNoGroupView.swift
  Carmu/Sources/Views/SessionStart/SessionStartMidView.swift
  Carmu/Sources/Views/SessionStart/SessionStartView.swift
Labels: Feat, Design, Refactor

#169 [Chore] User 관련 코드 기획 변경사항 적용
  Carmu.xcodeproj/project.pbxproj
  Carmu.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Carmu/Assets.xcassets/ProfileImages/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileAqua.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileAqua.imageset/profileAqua.png
  Carmu/Assets.xcassets/ProfileImages/profileAquaBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileAquaBlue.imageset/profileAquaBlue.png
  Carmu/Assets.xcassets/ProfileImages/profileBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileBlue.imageset/profileBlue.png
  Carmu/Assets.xcassets/ProfileImages/profileDarkNavy.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileDarkNavy.imageset/profileDarkNavy.png
  Carmu/Assets.xcassets/ProfileImages/profileGray.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileGray.imageset/profileGray.png
  Carmu/Assets.xcassets/ProfileImages/profileGreen.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileGreen.imageset/profileGreen.png
  Carmu/Assets.xcassets/ProfileImages/profileNavy.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileNavy.imageset/profileNavy.png
  Carmu/Assets.xcassets/ProfileImages/profileOrangeBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileOrangeBlue.imageset/profileOrangeBlue.png
  Carmu/Assets.xcassets/ProfileImages/profilePurpleBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profilePurpleBlue.imageset/profilePurpleBlue.png
  Carmu/Assets.xcassets/ProfileImages/profileRed.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileRed.imageset/profileRed.png
  Carmu/Assets.xcassets/ProfileImages/profileRedBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileRedBlue.imageset/profileRedBlue.png
  Carmu/Assets.xcassets/ProfileImages/profileYellow.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/profileYellow.imageset/profileYellow.png
  Carmu/Sources/Controllers/LoginViewController.swift
  Carmu/Sources/Controllers/MyPage/FriendAddViewController.swift
  Carmu/Sources/Controllers/MyPage/FriendDetailViewController.swift
  Carmu/Sources/Controllers/MyPage/FriendListViewController.swift
  Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
  Carmu/Sources/Controllers/MyPage/ProfileChangeViewController.swift
  Carmu/Sources/Models/DTO/ProfileType.swift
  Carmu/Sources/Models/DTO/User.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/MyPage/FriendDetailView.swift
  Carmu/Sources/Views/MyPage/FriendListTableViewCell.swift
  Carmu/Sources/Views/MyPage/MyPageView.swift
  Carmu/Sources/Views/MyPage/ProfileChangeView.swift
Labels: Feat, Chore

#170 [Feat] 크루 생성 - 출발지/도착지 주소설정 뷰 구현(운전자)
  Carmu.xcodeproj/project.pbxproj
  Carmu.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
  Carmu/Sources/Controllers/CrewMake/Crew/PositionSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Crew/StopoverPointCheckViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/SelectAddressViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/SelectDetailPointMapViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelectViewController.swift
  Carmu/Sources/Models/DTO/AddressDTO.swift
  Carmu/Sources/Models/DTO/SelectAddressDTO.swift
  Carmu/Sources/Views/CrewMake/Crew/BoardingPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Crew/InviteCodeInputView.swift
  Carmu/Sources/Views/CrewMake/Crew/PositionSelectView.swift
  Carmu/Sources/Views/CrewMake/Crew/StopoverPointCheckView.swift
  Carmu/Sources/Views/CrewMake/Driver/Cell/DefaultAddressTableViewCell.swift
  Carmu/Sources/Views/CrewMake/Driver/Cell/SelectAddressTableViewCell.swift
  Carmu/Sources/Views/CrewMake/Driver/SelectAddressView.swift
  Carmu/Sources/Views/CrewMake/Driver/SelectDetailPointMapView.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelectView.swift
Labels: Feat, Design

#174 [Refactor] 그룹 -> 크루 워딩 변경
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/SessionStartView/NoCrewBlinker.imageset/Contents.json
  Carmu/Assets.xcassets/SessionStartView/NoCrewBlinker.imageset/NoCrewBlinker.png
  Carmu/Sources/Controllers/SessionStart/SessionMapView/SessionMapViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Models/DTO/User.swift
  Carmu/Sources/Models/KeychainItem.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/SessionStart/SessionStartMidNoCrewView.swift
  Carmu/Sources/Views/SessionStart/SessionStartView.swift
Labels: Refactor

#175 [Feat] 크루 생성 - 남은 화면 제목 - 다음버튼만 있는 화면으로 구현
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelectViewController.swift
  Carmu/Sources/Views/CrewMake/Driver/CodeShareView.swift
  Carmu/Sources/Views/CrewMake/Driver/FinalConfirmView.swift
  Carmu/Sources/Views/CrewMake/Driver/RepeatDaySelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/SelectDetailPointMapView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelectView.swift
Labels: Feat

#180 [Feat] 메인 화면에 필요한 데이터 추가
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DTO/Point.swift
  Carmu/Sources/Models/DTO/Session.swift
  Carmu/Sources/Models/DTO/User.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
  Carmu/Sources/Views/SessionStart/SessionStartNoCrewView.swift
  Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
Labels: Feat, Chore

#179 [Feat] 크루 생성 화면 Navigation 연결, SceneDelegate 분기 처리
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
  Carmu/Sources/Controllers/CrewMake/Crew/PositionSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/PositionSelectViewController.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Views/CrewMake/Crew/BoardingPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Crew/InviteCodeInputView.swift
  Carmu/Sources/Views/CrewMake/Driver/CodeShareView.swift
  Carmu/Sources/Views/CrewMake/Driver/FinalConfirmView.swift
  Carmu/Sources/Views/CrewMake/Driver/RepeatDaySelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/StopoverPointCheckView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelectView.swift
  Carmu/Sources/Views/CrewMake/PositionSelectView.swift
Labels: Feat

#182 [Feat] 유저 프로필 수정 기능 구현
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/ProfileImages/Selected/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileAqua.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileAqua.imageset/selectedProfileAqua.png
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileAquaBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileAquaBlue.imageset/selectedProfileAquaBlue.png
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileBlue.imageset/selectedProfileBlue.png
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileDarkNavy.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileDarkNavy.imageset/selectedProfileDarkNavy.png
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileGray.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileGray.imageset/selectedProfileGray.png
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileGreen.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileGreen.imageset/selectedProfileGreen.png
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileNavy.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileNavy.imageset/selectedProfileNavy.png
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileOrangeBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileOrangeBlue.imageset/selectedProfileOrangeBlue.png
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfilePurpleBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfilePurpleBlue.imageset/selectedProfilePurpleBlue.png
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileRed.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileRed.imageset/selectedProfileRed.png
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileRedBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileRedBlue.imageset/selectedProfileRedBlue.png
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileYellow.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/Selected/selectedProfileYellow.imageset/selectedProfileYellow.png
  Carmu/Sources/Controllers/MyPage/FriendAddViewController.swift
  Carmu/Sources/Controllers/MyPage/FriendDetailViewController.swift
  Carmu/Sources/Controllers/MyPage/FriendListViewController.swift
  Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
  Carmu/Sources/Controllers/MyPage/ProfileChangeViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/InquiryViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/PrivacyViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
  Carmu/Sources/Extensions/String+Extension.swift
  Carmu/Sources/Extensions/UIImage+Extension.swift
  Carmu/Sources/Models/DTO/ProfileType.swift
  Carmu/Sources/Models/DTO/User.swift
  Carmu/Sources/Models/ProfileImageColor.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/MyPage/FriendDetailView.swift
  Carmu/Sources/Views/MyPage/FriendListTableViewCell.swift
  Carmu/Sources/Views/MyPage/MyPageView.swift
  Carmu/Sources/Views/MyPage/ProfileChangeView.swift
  Carmu/Sources/Views/MyPage/ProfileImageColorCollectionViewCell.swift
  Carmu/Sources/Views/MyPage/Settings/InquiryView.swift
  Carmu/Sources/Views/MyPage/Settings/PrivacyView.swift
  Carmu/Sources/Views/MyPage/Settings/SettingsView.swift
Labels: Feat, Design, Chore

#184 [Feat] 운전자의 크루생성 마지막 화면에서 더미 크루 데이터 Firebase DB에 저장
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Models/DTO/Point.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Feat

#185 Bazzi/feat/#153
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectAddressViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectModalViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
  Carmu/Sources/Extensions/Date+Extension.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Models/DTO/Point.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectAddressView.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapView.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectCellView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectModalView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectView.swift
Labels: Feat, Design

#188 [Feat] 운행하지 않을 때의 화면 구성
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/SessionStartView/noSessionBlinker.imageset/Contents.json
  Carmu/Assets.xcassets/SessionStartView/noSessionBlinker.imageset/noSessionBlinker.png
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Extensions/UIViewController+Extension.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Models/DTO/Point.swift
  Carmu/Sources/Models/DTO/Session.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/MyPage/MyPageView.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
  Carmu/Sources/Views/SessionStart/SessionStartNoCrewView.swift
  Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
  Carmu/Sources/Views/SessionStart/SessionStartView.swift
Labels: Feat, Design, Chore, Refactor

#192 [Feat] 크루 생성 - 반복 요일 설정 화면 구현(운전자)
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
  Carmu/Sources/Extensions/Date+Extension.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Utils/ButtonComponent/DaySelectButton.swift
  Carmu/Sources/Utils/ButtonComponent/LargeSelectButton.swift
  Carmu/Sources/Utils/ButtonComponent/NextButton.swift
  Carmu/Sources/Utils/ButtonComponent/StopoverSelectButton.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/RepeatDaySelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectCellView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectModalView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectView.swift
Labels: Feat, Design

#193 [Feat] 크루 데이터 변경
  Carmu/Assets.xcassets/SessionStartView/NoSessionBlinker.imageset/Contents.json
  Carmu/Assets.xcassets/SessionStartView/NoSessionBlinker.imageset/NoSessionBlinker.png
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Feat

#194 [Feat] 동승자가 따로 가요를 클릭했을 때의 화면
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
Labels: Feat

#195 [Refactor] MapViewController에서 레이아웃 관련 코드 MapView로 분리
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Views/Map/MapDetailView.swift
  Carmu/Sources/Views/Map/MapView.swift
  Carmu/Sources/Views/Map/TimeDataView.swift
Labels: Refactor

#196 [Feat] 크루 생성 - 최종 확인 화면 구현(운전자)
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Utils/ButtonComponent/RightNavigationBarButton.swift
  Carmu/Sources/Views/CrewMake/Driver/FinalConfirmView.swift
Labels: Feat, Design

#201 [Feat] 크루 생성 - 공유화면 구현(운전자)
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/Character/CheekAqua.imageset/CheekAqua.png
  Carmu/Assets.xcassets/Character/CheekAqua.imageset/Contents.json
  Carmu/Assets.xcassets/Character/CheekBlue.imageset/CheekBlue.png
  Carmu/Assets.xcassets/Character/CheekBlue.imageset/Contents.json
  Carmu/Assets.xcassets/Character/CheekNone.imageset/CheekNone.png
  Carmu/Assets.xcassets/Character/CheekNone.imageset/Contents.json
  Carmu/Assets.xcassets/Character/CheekRed.imageset/CheekRed.png
  Carmu/Assets.xcassets/Character/CheekRed.imageset/Contents.json
  Carmu/Assets.xcassets/Character/CheekYellow.imageset/CheekYellow.png
  Carmu/Assets.xcassets/Character/CheekYellow.imageset/Contents.json
  Carmu/Assets.xcassets/Character/Contents.json
  Carmu/Assets.xcassets/Character/VariantGradientStroke.imageset/Contents.json
  Carmu/Assets.xcassets/Character/VariantGradientStroke.imageset/VariantGradientStroke.png
  Carmu/Assets.xcassets/Character/VariantLookUp.imageset/Contents.json
  Carmu/Assets.xcassets/Character/VariantLookUp.imageset/VariantLookUp.png
  Carmu/Assets.xcassets/Character/VariantStroke.imageset/Contents.json
  Carmu/Assets.xcassets/Character/VariantStroke.imageset/VariantStroke.png
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Models/DayOfWeek.swift
  Carmu/Sources/Views/CrewMake/Crew/BoardingPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/CodeShareView.swift
  Carmu/Sources/Views/CrewMake/Driver/FinalConfirmView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectView.swift
Labels: Feat, Design, Refactor

#202 [Feat] 카카오톡, 인스타그램, iMessage, 라인 공유버튼 누를 때 메시지 보내는 기능 추가
  Carmu/Assets.xcassets/ColorAsset/Black&White/Trans60.colorset/Contents.json
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Models/Color/ColorTheme.swift
  Carmu/Sources/Views/CrewMake/Driver/CodeShareView.swift
Labels: Feat, Design

#203 [Design] 마이페이지 및 설정 화면 UI 수정
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/Character/LoadingCharacterRed.imageset/Contents.json
  Carmu/Assets.xcassets/Character/LoadingCharacterRed.imageset/LoadingCharacterRed.png
  Carmu/Assets.xcassets/ColorAsset/BlueScale/BlueTrans20.colorset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileAqua.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileAqua.imageset/myPageProfileAqua.png
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileAquaBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileAquaBlue.imageset/myPageProfileAquaBlue.png
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileBlue.imageset/myPageProfileBlue.png
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileDarkNavy.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileDarkNavy.imageset/myPageProfileDarkNavy.png
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileGray.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileGray.imageset/myPageProfileGray.png
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileGreen.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileGreen.imageset/myPageProfileGreen.png
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileNavy.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileNavy.imageset/myPageProfileNavy.png
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileOrangeBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileOrangeBlue.imageset/myPageProfileOrangeBlue.png
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfilePurpleBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfilePurpleBlue.imageset/myPageProfilePurpleBlue.png
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileRed.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileRed.imageset/myPageProfileRed.png
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileRedBlue.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileRedBlue.imageset/myPageProfileRedBlue.png
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileYellow.imageset/Contents.json
  Carmu/Assets.xcassets/ProfileImages/MyPage/myPageProfileYellow.imageset/myPageProfileYellow.png
  Carmu/Assets.xcassets/appLogo.imageset/appLogo.png
  Carmu/Assets.xcassets/appLogo.imageset/logo.png
  Carmu/Assets.xcassets/cameraBtn.imageset/cameraBtn.png
  Carmu/Assets.xcassets/profileEditBtn.imageset/Contents.json
  Carmu/Assets.xcassets/profileEditBtn.imageset/profileEditBtn.png
  Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
  Carmu/Sources/Controllers/MyPage/NicknameEditViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/InquiryViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/PrivacyViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
  Carmu/Sources/Extensions/UIImage+Extension.swift
  Carmu/Sources/Models/Color/SemanticColor.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Utils/CrewMakeUtil.swift
  Carmu/Sources/Utils/CustomVisualEffectView.swift
  Carmu/Sources/Views/MyPage/CrewInfo/CrewInfoDriverView.swift
  Carmu/Sources/Views/MyPage/CrewInfo/CrewInfoNoCrewView.swift
  Carmu/Sources/Views/MyPage/CrewInfo/CrewInfoPassengerView.swift
  Carmu/Sources/Views/MyPage/CustomIntensityVisualEffectView.swift
  Carmu/Sources/Views/MyPage/FriendDetailView.swift
  Carmu/Sources/Views/MyPage/GiftCardCollectionViewCell.swift
  Carmu/Sources/Views/MyPage/MyPageView.swift
  Carmu/Sources/Views/MyPage/NicknameEditView.swift
  Carmu/Sources/Views/MyPage/Settings/SettingsView.swift
Labels: Feat, Design, Refactor

#204 [Design] 메인화면 뒷면 뷰 디자인
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/SessionStartView/LocationStick.imageset/Contents.json
  Carmu/Assets.xcassets/SessionStartView/LocationStick.imageset/LocationStick.png
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Views/SessionStart/SessionStartBackView.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
  Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
Labels: Feat, Design

#206 [refactor] FirebaseManager 메서드 정리 & 미사용 소스코드 파일 삭제
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/MyPage/FriendAddViewController.swift
  Carmu/Sources/Controllers/MyPage/FriendDetailViewController.swift
  Carmu/Sources/Controllers/MyPage/FriendListViewController.swift
  Carmu/Sources/Controllers/MyPage/NicknameEditViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/MyPage/FriendAddView.swift
  Carmu/Sources/Views/MyPage/FriendDetailView.swift
  Carmu/Sources/Views/MyPage/FriendListTableViewCell.swift
  Carmu/Sources/Views/MyPage/FriendListView.swift
  Carmu/Sources/Views/MyPage/NoSearchedResultTableViewCell.swift
Labels: Feat, Chore, Refactor

#210 [Feat] 크루 생성 - 경유지 설정 화면 구현(운전자)
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Utils/ButtonComponent/AddressSelectButtonView.swift
  Carmu/Sources/Utils/ButtonComponent/SelectAddressButtonProtocol.swift
  Carmu/Sources/Utils/ButtonComponent/StopoverPointAddButtonView.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectView.swift
Labels: Feat, Design

#211 [Design] 앞면 뷰 인원 배치
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Views/SessionStart/CrewCollectionViewCell.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
Labels: Feat, Design

#216 [Feat] 운행해요 -> 맵뷰 관련 로직 구현 (운전자)
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Views/SessionStart/CrewCollectionViewCell.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
  Carmu/Sources/Views/SessionStart/SessionStartView.swift
Labels: Feat

#219 [Feat] 마이페이지 크루 정보 확인 뷰 및 기능 추가
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
  Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
  Carmu/Sources/Controllers/MyPage/NameEditViewController.swift
  Carmu/Sources/Controllers/MyPage/NicknameEditViewController.swift
  Carmu/Sources/Models/Color/ColorTheme.swift
  Carmu/Sources/Views/MyPage/CrewEdit/CrewInfoCheckView.swift
  Carmu/Sources/Views/MyPage/CrewInfo/GiftCardCollectionViewCell.swift
  Carmu/Sources/Views/MyPage/MyPageView.swift
  Carmu/Sources/Views/MyPage/NameEditView.swift
Labels: Feat, Design

#220 [Feat] 규칙 설명 팝업 생성
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/SessionStart/RuleDescriptionViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Views/SessionStart/RuleDescriptionView.swift
  Carmu/Sources/Views/SessionStart/SessionStartNoCrewView.swift
Labels: Feat

#222 [Design] 변경된 디자인에 맞춰 맵뷰 수정
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/mapView/car.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/car.imageset/car.png
  Carmu/Assets.xcassets/mapView/destinationTapped.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/destinationTapped.imageset/destinationTapped.png
  Carmu/Assets.xcassets/mapView/pickupLocation1.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/pickupLocation1.imageset/pickupLocation1.png
  Carmu/Assets.xcassets/mapView/pickupLocation1Tapped.imageset/pickupLocation1Tapped.png
  Carmu/Assets.xcassets/mapView/pickupLocation2.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/pickupLocation2.imageset/pickupLocation2.png
  Carmu/Assets.xcassets/mapView/pickupLocation2Tapped.imageset/pickupLocation2Tapped.png
  Carmu/Assets.xcassets/mapView/pickupLocation3.imageset/pickupLocation3.png
  Carmu/Assets.xcassets/mapView/pickupLocation3Tapped.imageset/pickupLocation3Tapped.png
  Carmu/Assets.xcassets/mapView/startingPoint.imageset/startingPoint.png
  Carmu/Assets.xcassets/mapView/startingPointTapped.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/startingPointTapped.imageset/startingPointTapped.png
  Carmu/Assets.xcassets/mapView/stopover1.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/stopover1.imageset/stopover1.png
  Carmu/Assets.xcassets/mapView/stopover2.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/stopover2.imageset/stopover2.png
  Carmu/Assets.xcassets/mapView/stopover3.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/stopover3.imageset/stopover3.png
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Controllers/Map/NoticeLateViewController.swift
  Carmu/Sources/Views/Map/CrewScrollView.swift
  Carmu/Sources/Views/Map/MapDetailView.swift
  Carmu/Sources/Views/Map/MapView.swift
  Carmu/Sources/Views/Map/NoticeLateView.swift
Labels: Feat, Design

#223 [Feat] 크루 생성 - 경유지 설정 화면과 상세 위치 설정 화면과의 연결
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/DetailPointMap/CenterMarker.imageset/CenterMarker.png
  Carmu/Assets.xcassets/DetailPointMap/centerMarker.imageset/Contents.json
  Carmu/Assets.xcassets/DetailPointMap/centerMarker.imageset/centerMarker.png
  Carmu/Assets.xcassets/DetailPointMap/modalXButton.imageset/Contents.json
  Carmu/Assets.xcassets/DetailPointMap/modalXButton.imageset/modalXButton.png
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapView.swift
  Carmu/Sources/Views/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointView.swift
Labels: Feat, Design

#225 [Feat] 놓친 부분 수정 및 리팩토링
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Views/SessionStart/SessionStartBackView.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
  Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
  Carmu/Sources/Views/SessionStart/StopOverInfoLeftView.swift
  Carmu/Sources/Views/SessionStart/StopOverInfoRightView.swift
Labels: Feat

#231 [Feat] 마이페이지 크루 정보 확인 화면 데이터 연결
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Utils/ButtonComponent/StopoverSelectButton.swift
  Carmu/Sources/Views/MyPage/CrewEdit/CrewEditView.swift
  Carmu/Sources/Views/MyPage/CrewEdit/CrewInfoCheckView.swift
Labels: Feat

#232 [Feat] 크루 생성 화면 실 데이터 생성 작업
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/PositionSelectViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Models/DTO/Point.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/CrewMake/Driver/FinalConfirmView.swift
  Carmu/Sources/Views/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectView.swift
Labels: Feat

#233 [HOTFIX] #232 머지 이후 옵셔널 처리 수정
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
Labels: Fix

#234 [Refactor] SessionStartViewController 리팩토링
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
Labels: Refactor

#237 [Feat] 동승자 그룹 코드 확인 후 해당 크루에 등록하는 로직 추가
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/CrewMake/Crew/BoardingPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Crew/InviteCodeInputView.swift
Labels: Feat

#240 [Feat] NextButton 유효성 검사 후 enable 처리
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
  Carmu/Sources/Views/CrewMake/Crew/BoardingPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Crew/InviteCodeInputView.swift
  Carmu/Sources/Views/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapView.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectModalView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectView.swift
Labels: Feat

#241 [Feat] SceneDelegate Auth 변수 @State 처럼 기능하도록 변경
  Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
  Carmu/Sources/SceneDelegate.swift
Labels: Fix, Feat

#243 [Feat] Firebase 연동 확인, 크루 생성까지의 플로우 확인, 실제 데이터로 수정 - 운전자
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/LoginViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
  Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Models/DTO/CrewStatus.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/SessionStart/SessionStartBackView.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
  Carmu/Sources/Views/SessionStart/StopoverInfoLeftView.swift
  Carmu/Sources/Views/SessionStart/StopoverInfoRightView.swift
Labels: Feat

#246 [Design] 주소 검색, 상세 위치 설정뷰(출발/도착지 하위) 디자인 수정
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectAddressViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
  Carmu/Sources/Utils/ButtonComponent/AddressSelectButtonView.swift
  Carmu/Sources/Views/CrewMake/Driver/Cell/DefaultAddressTableViewCell.swift
  Carmu/Sources/Views/CrewMake/Driver/Cell/SelectAddressTableViewCell.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectAddressView.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapView.swift
Labels: Fix, Design

#247 [Feat] crewStatus 변경 및 collectionView에 적용
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Models/DTO/MemeberStatus.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
Labels: Feat

#249 [Feat] 마이페이지 크루 편집 화면 개발
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/RepeatDaySelectModalViewController.swift
  Carmu/Sources/Views/MyPage/CrewEdit/CrewEditView.swift
  Carmu/Sources/Views/MyPage/CrewEdit/CrewInfoCheckView.swift
  Carmu/Sources/Views/MyPage/CrewEdit/DayButtonCollectionViewCell.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/AddressEditButton.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/PointEditView.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/PointType.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/TimeEditButton.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/TimeType.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/TimeTypeLabel.swift
  Carmu/Sources/Views/MyPage/CrewEdit/RepeatDaySelectModalView.swift
Labels: Feat, Design

#250 [Feat] 맵뷰 나머지 기능 구현
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/SessionStartView/carmuLogoSmall.imageset/Contents.json
  Carmu/Assets.xcassets/SessionStartView/carmuLogoSmall.imageset/carmuLogoSmall.png
  Carmu/Assets.xcassets/SessionStartView/characterDriver.imageset/Contents.json
  Carmu/Assets.xcassets/SessionStartView/characterDriver.imageset/characterDriver.png
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionFinishViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Views/Map/MapDetailView.swift
  Carmu/Sources/Views/Map/MapView.swift
Labels: Feat

#256 [Feat] Firebase 연동 - 동승자
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
Labels: Feat

#257 [Chore] 린트 룰 수정
  .swiftlint.yml
  Carmu/Sources/AppDelegate.swift
  Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectAddressViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
  Carmu/Sources/Controllers/LoginViewController.swift
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Controllers/Map/NoticeLateViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/RepeatDaySelectModalViewController.swift
  Carmu/Sources/Controllers/MyPage/NameEditViewController.swift
  Carmu/Sources/Controllers/MyPage/ProfileChangeViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/InquiryViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Views/CrewMake/Driver/CodeShareView.swift
  Carmu/Sources/Views/CrewMake/Driver/StopoverPointCheckView.swift
  Carmu/Sources/Views/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectView.swift
  Carmu/Sources/Views/CrewMake/PositionSelectView.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
  Carmu/Sources/Views/SessionStart/SessionStartNoCrewView.swift
  Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
Labels: Chore, Refactor

#258 [Feat] 마이페이지 크루 편집 화면 상세주소 설정 뷰 연결
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
  Carmu/Sources/Views/MyPage/CrewEdit/CrewEditView.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/AddressEditButton.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/PointEditView.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/PointType.swift
Labels: Feat

#261 [Design] 맵뷰 경로선 패턴 변경
  Carmu/Assets.xcassets/mapView/triangle.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/triangle.imageset/triangle.png
  Carmu/Sources/Controllers/Map/MapViewController.swift
Labels: Design

#263 [Feat] 맵뷰에 나의 현재 위치 표시
  Carmu/Assets.xcassets/mapView/currentLocation.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/currentLocation.imageset/currentLocation.png
  Carmu/Assets.xcassets/mapView/myPosition.imageset/Contents.json
  Carmu/Assets.xcassets/mapView/myPosition.imageset/myPosition.png
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Views/Map/MapView.swift
Labels: Feat

#264 [Feat] 이전 PR 피드백 반영
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Views/SessionStart/SessionStartBackView.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
  Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
  Carmu/Sources/Views/SessionStart/StopoverInfoLeftView.swift
  Carmu/Sources/Views/SessionStart/StopoverInfoRightView.swift
Labels: Feat

#265 [Feat] @objc 및 관련 메서드들 Firebase 데이터로 변경 (동승자)
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Models/DTO/MemberStatus.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/SessionStart/SessionStartBackView.swift
Labels: Feat

#267 [Refactor] 크루 편집 화면 테이블뷰로 수정
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Views/MyPage/CrewEdit/CrewEditView.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/AddressEditButton.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/PointEditTableViewCell.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/PointEditView.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/PointType.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/TimeEditButton.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/TimeTypeLabel.swift
Labels: Feat, Refactor

#269 [Feat] 미반영 기능 적용, 텍스트 등 자잘한 디자인 업데이트
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/Content/Contents.json
  Carmu/Assets.xcassets/Content/loadingContent1.imageset/Contents.json
  Carmu/Assets.xcassets/Content/loadingContent1.imageset/loadingContent1.png
  Carmu/Assets.xcassets/Content/loadingContent2.imageset/Contents.json
  Carmu/Assets.xcassets/Content/loadingContent2.imageset/loadingContent2.png
  Carmu/Assets.xcassets/Content/loadingContent3.imageset/Contents.json
  Carmu/Assets.xcassets/Content/loadingContent3.imageset/loadingContent3.png
  Carmu/Assets.xcassets/Content/loadingContent4.imageset/Contents.json
  Carmu/Assets.xcassets/Content/loadingContent4.imageset/loadingContent4.png
  Carmu/Assets.xcassets/DetailPointMap/modalXButton.imageset/modalXButton.png
  Carmu/Assets.xcassets/DetailPointMap/navigationBackButton.imageset/Contents.json
  Carmu/Assets.xcassets/DetailPointMap/navigationBackButton.imageset/navigationBackButton.png
  Carmu/Sources/AppDelegate.swift
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectAddressViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectModalViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/PositionSelectViewController.swift
  Carmu/Sources/Controllers/LoadingViewController.swift
  Carmu/Sources/Utils/ButtonComponent/AddressSelectButtonView.swift
  Carmu/Sources/Utils/CrewMakeUtil.swift
  Carmu/Sources/Views/CrewMake/Crew/BoardingPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Crew/InviteCodeInputView.swift
  Carmu/Sources/Views/CrewMake/Driver/CodeShareView.swift
  Carmu/Sources/Views/CrewMake/Driver/FinalConfirmView.swift
  Carmu/Sources/Views/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectAddressView.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapView.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/StopoverPointCheckView.swift
  Carmu/Sources/Views/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointView.swift
  Carmu/Sources/Views/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectCellView.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectView.swift
  Carmu/Sources/Views/CrewMake/PositionSelectView.swift
  Carmu/Sources/Views/LoadingView.swift
Labels: Fix, Feat, Design, Del, Chore, Refactor

#270 [Feat] @objc 및 관련 메서드들 Firebase 데이터로 변경 (운전자)
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
Labels: Feat, Refactor

#280 [Feat] 화면에 데이터 즉각 반영
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
  Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
  Carmu/Sources/Views/SessionStart/SessionStartView.swift
Labels: Feat

#281 [Feat] MemberStatus Firebase에 올리기
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Feat

#283 [Fix] 경유지 설정 뷰 관련 버그 수정
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
Labels: Fix

#284 [Refactor] updateUI 시점 재구성
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Feat

#287 [Feat] 크루 이름 생성하기 화면 구현
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Driver/CrewNameSettingViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/PositionSelectViewController.swift
  Carmu/Sources/Views/CrewMake/Driver/CrewNameSettingView.swift
Labels: Feat

#288 [Feat] 맵뷰 DB 연동
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Extensions/Date+Extension.swift
  Carmu/Sources/Extensions/UIStackView+Extension.swift
  Carmu/Sources/Models/DTO/Coordinate.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/Map/CrewScrollView.swift
  Carmu/Sources/Views/Map/MapDetailView.swift
  Carmu/Sources/Views/Map/MapView.swift
Labels: Feat

#290 [Feat] reverseGeocoding Naver Map 활용으로 변경
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
Labels: Feat

#291 [Feat] 크루 없을 때 -> 크루 생성하기 화면 연결
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/SessionStart/SessionStartNoCrewView.swift
Labels: Feat

#295 [Feat] 공통 미반영 작업 추가
  Carmu.xcodeproj/project.pbxproj
  Carmu/Assets.xcassets/AppIcon.appiconset/100.png
  Carmu/Assets.xcassets/AppIcon.appiconset/1024.png
  Carmu/Assets.xcassets/AppIcon.appiconset/114.png
  Carmu/Assets.xcassets/AppIcon.appiconset/120.png
  Carmu/Assets.xcassets/AppIcon.appiconset/128.png
  Carmu/Assets.xcassets/AppIcon.appiconset/144.png
  Carmu/Assets.xcassets/AppIcon.appiconset/152.png
  Carmu/Assets.xcassets/AppIcon.appiconset/16.png
  Carmu/Assets.xcassets/AppIcon.appiconset/167.png
  Carmu/Assets.xcassets/AppIcon.appiconset/172.png
  Carmu/Assets.xcassets/AppIcon.appiconset/180.png
  Carmu/Assets.xcassets/AppIcon.appiconset/196.png
  Carmu/Assets.xcassets/AppIcon.appiconset/20.png
  Carmu/Assets.xcassets/AppIcon.appiconset/216.png
  Carmu/Assets.xcassets/AppIcon.appiconset/256.png
  Carmu/Assets.xcassets/AppIcon.appiconset/29.png
  Carmu/Assets.xcassets/AppIcon.appiconset/32.png
  Carmu/Assets.xcassets/AppIcon.appiconset/40.png
  Carmu/Assets.xcassets/AppIcon.appiconset/48.png
  Carmu/Assets.xcassets/AppIcon.appiconset/50.png
  Carmu/Assets.xcassets/AppIcon.appiconset/512.png
  Carmu/Assets.xcassets/AppIcon.appiconset/55.png
  Carmu/Assets.xcassets/AppIcon.appiconset/57.png
  Carmu/Assets.xcassets/AppIcon.appiconset/58.png
  Carmu/Assets.xcassets/AppIcon.appiconset/60.png
  Carmu/Assets.xcassets/AppIcon.appiconset/64.png
  Carmu/Assets.xcassets/AppIcon.appiconset/66.png
  Carmu/Assets.xcassets/AppIcon.appiconset/72.png
  Carmu/Assets.xcassets/AppIcon.appiconset/76.png
  Carmu/Assets.xcassets/AppIcon.appiconset/80.png
  Carmu/Assets.xcassets/AppIcon.appiconset/87.png
  Carmu/Assets.xcassets/AppIcon.appiconset/88.png
  Carmu/Assets.xcassets/AppIcon.appiconset/92.png
  Carmu/Assets.xcassets/AppIcon.appiconset/Contents.json
  Carmu/Assets.xcassets/LaunchScreen/Contents.json
  Carmu/Assets.xcassets/LaunchScreen/launchSlogan.imageset/Contents.json
  Carmu/Assets.xcassets/LaunchScreen/launchSlogan.imageset/launchSlogan.png
  Carmu/Base.lproj/LaunchScreen.storyboard
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/CrewNameSettingViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
  Carmu/Sources/Controllers/Loading/LaunchScreenViewController.swift
  Carmu/Sources/Controllers/Loading/LoadingViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Extensions/UIImage+Extension.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Utils/GifView.swift
  Carmu/Sources/Views/Loading/LaunchScreenView.swift
  Carmu/Sources/Views/Loading/LoadingView.swift
Labels: Fix, Feat, Design

#296 [Feat] 주소 검색 화면 셀 탭 시 하이라이트 처리 기능 추가
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectAddressViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/SelectDetailPointMapViewController.swift
  Carmu/Sources/Views/CrewMake/Driver/Cell/DefaultAddressTableViewCell.swift
  Carmu/Sources/Views/CrewMake/Driver/Cell/SelectAddressTableViewCell.swift
  Carmu/Sources/Views/CrewMake/Driver/StartEndPointSelect/SelectAddressView.swift
Labels: Fix, Feat

#297 [Feat] 서버 푸시 알림 구현 및 파이어베이스 메서드 수정
  Carmu.xcodeproj/project.pbxproj
  Carmu/Resources/launchGif.gif
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Utils/ServerPushManager.swift
Labels: Feat

#300 [Feat] 맵뷰 '지각 알리기' 관련 처리
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Controllers/Map/NoticeLateViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Models/DTO/MemberStatus.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/Map/CrewScrollView.swift
  Carmu/Sources/Views/Map/MapDetailView.swift
Labels: Feat

#303 [Feat] 크루 편집 화면 UI 수정 및 크루명 편집 구현
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/LoginViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
  Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/AddressEditButton.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/PointType.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/StopoverAddButton.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/StopoverRemoveButton.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/TimeEditButton.swift
Labels: Feat, Design

#304 [Feat] 현재 나타나는 오류 수정
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/CrewNameSettingViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/FinalConfirmViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StartEndPointSelect/StartEndPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/StopoverPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
  Carmu/Sources/Controllers/LoginViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/SessionStart/SessionStartBackView.swift
Labels: Feat

#306 [Feat] 도착 시간 10분 뒤 자동 종료
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionFinishViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Extensions/String+Extension.swift
  Carmu/Sources/Models/DTO/Crew.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/Map/MapDetailView.swift
Labels: Feat

#310 [Feat] 위치권한 관련 설정
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
Labels: Feat

#311 [Feat] 크루 나가기 구현
  Carmu/Sources/Controllers/LoginViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
  Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Feat, Refactor

#312 [Refactor] FirebaseManager의 친구 관련 메서드 정리 및 앱 진입 시 로직 오류 수정
  Carmu.xcodeproj/project.pbxproj
  Carmu.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Carmu/Sources/Controllers/Map/NoticeLateViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
  Carmu/Sources/Models/DTO/Friendship.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Fix, Refactor

#314 [Feat] 서버 푸시
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Controllers/Map/NoticeLateViewController.swift
  Carmu/Sources/Utils/ServerPushManager.swift
Labels: Feat

#316 [feat] SessionStartBackView 변경 및 기타 작업 수정
  Carmu/Sources/Controllers/SessionStart/RuleDescriptionViewController.swift
  Carmu/Sources/Models/Font/CarmuFont.swift
  Carmu/Sources/Views/SessionStart/RuleDescriptionView.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
  Carmu/Sources/Views/SessionStart/SessionStartNoCrewView.swift
  Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
Labels: Feat

#319 [Feat] 크루 편집 & 셔틀 나가기 & 초대코드로 셔틀 그룹 입장 시 화면 처리
  Carmu.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
  Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Views/MyPage/CrewEdit/CrewInfoCheckView.swift
Labels: Fix, Feat, Refactor

#322 [Feat] 시간 선택 뷰 이전 장소보다 더 늦은 시간으로만 설정되는 기능 추가
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectModalViewController.swift
  Carmu/Sources/Controllers/CrewMake/Driver/TimeSelect/TimeSelectViewController.swift
  Carmu/Sources/Controllers/CrewMake/PositionSelectViewController.swift
  Carmu/Sources/Views/CrewMake/Driver/TimeSelect/TimeSelectModalView.swift
Labels: Fix, Feat

#325 [Fix] 크루 편집 시 주소 설정 지도뷰 교체
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
Labels: Fix, Feat, Design

#326 [Feat] 버튼 눌렀을 때 하이라이트 표시
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Extensions/UIButton+Extension.swift
  Carmu/Sources/Models/Color/SemanticColor.swift
  Carmu/Sources/Views/SessionStart/SessionStartView.swift
Labels: Feat

#328 [Design] 마이페이지 디자인 수정
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
  Carmu/Sources/Controllers/MyPage/MyPageViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/InquiryViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/PrivacyViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/QuestionDetailViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Views/MyPage/CrewEdit/CrewEditView.swift
  Carmu/Sources/Views/MyPage/CrewEdit/CrewInfoCheckView.swift
  Carmu/Sources/Views/MyPage/CrewEdit/PointEdit/PointEditTableViewCell.swift
  Carmu/Sources/Views/MyPage/CrewInfo/CrewInfoDriverView.swift
  Carmu/Sources/Views/MyPage/CrewInfo/CrewInfoPassengerView.swift
  Carmu/Sources/Views/MyPage/CrewInfo/GiftCardCollectionViewCell.swift
  Carmu/Sources/Views/MyPage/Settings/InquiryView.swift
  Carmu/Sources/Views/MyPage/Settings/PrivacyView.swift
  Carmu/Sources/Views/MyPage/Settings/QuestionDetailView.swift
  Carmu/Sources/Views/MyPage/Settings/SettingsView.swift
Labels: Feat, Design

#330 [feat] #327 - 운전자가 운전을 포기한 경우 탑승자들에게 푸시 알림
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Utils/ServerPushManager.swift
Labels: Feat

#331 [Refactor] SessionStartView 리팩터링 및 버그 수정
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Driver/CodeShareViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Extensions/UIButton+Extension.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Utils/FirebaseManager.swift
  Carmu/Sources/Utils/LabelComponent/CarpoolPlanLabel.swift
  Carmu/Sources/Views/SessionStart/SessionStartDriverView.swift
  Carmu/Sources/Views/SessionStart/SessionStartPassengerView.swift
  Carmu/Sources/Views/SessionStart/SessionStartView.swift
Labels: Fix, Refactor

#338 [Fix] 탑승자가 포기하기 버튼 눌렀을 때 세션이 종료되어버림
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Fix

#341 [fix] #337 - 토스트 메세지 한 번만 나타나고 나타나지 않는 문제 해결
  Carmu/Sources/Controllers/Map/MapViewController.swift
  Carmu/Sources/Views/Map/MapView.swift
Labels: Fix

#340 [refactor] #333 - 뒷면 이미지로 변경
  Carmu/Assets.xcassets/SessionStartView/Rules.imageset/Contents.json
  Carmu/Assets.xcassets/SessionStartView/Rules.imageset/Rules.png
  Carmu/Sources/Views/SessionStart/SessionStartNoCrewView.swift
Labels: Refactor

#342 [Fix] StartView에서 SessionStatus가 sessionStart, MemberStatus가 decline일 때 버튼 버그 수정
  Carmu/Sources/Views/SessionStart/SessionStartView.swift
Labels: Fix

#344 [Feat] 개인정보 처리방침 & 자주 묻는 질문 화면 구성
  Carmu/Sources/Controllers/MyPage/Settings/InquiryViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/PrivacyViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/QuestionDetailViewController.swift
  Carmu/Sources/Views/MyPage/Settings/InquiryView.swift
  Carmu/Sources/Views/MyPage/Settings/PrivacyView.swift
  Carmu/Sources/Views/MyPage/Settings/QuestionDetailView.swift
Labels: Feat, Design

#343 [feat] #332 - 디바이스 토큰값 변경되면 갱신하는 메서드 생성
  Carmu/Sources/AppDelegate.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Feat

#345 [Fix] iPhone 8일 때의 Constraint 수정
  Carmu/Sources/Controllers/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectViewController.swift
  Carmu/Sources/Views/CrewMake/Driver/RepeatDaySelect/RepeatDaySelectView.swift
  Carmu/Sources/Views/SessionStart/SessionStartNoCrewView.swift
Labels: Fix

#346 [Fix] StartView에서 로딩중일 때 완성되지 않은 화면이 보이고 있음
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/SceneDelegate.swift
Labels: Fix

#348 [Fix] 따로가요, 함께가요 버튼 눌렀을시 Crash 발생하는 현상 수정
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Fix

#350 [Fix] 크루 나가기 버튼 누를 때 Out of bound 에러 발생
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Fix

#352 [Fix] 초대코드 입력 시 유효하지 않은 초대코드 입력해도 넘어가는 문제
  Carmu/Sources/Controllers/CrewMake/Crew/InviteCodeInputViewController.swift
  Carmu/Sources/Views/CrewMake/Crew/InviteCodeInputView.swift
Labels: Fix

#360 [Feat] MyPage 수정시 Crew의 MemberStatus도 수정
  Carmu/Sources/Controllers/MyPage/NameEditViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Feat

#363 [Feat] 셔틀이 운행되지 않는 요일일 때 화면 구현
  Carmu/Sources/Controllers/SessionStart/SessionStartViewController.swift
  Carmu/Sources/Extensions/Date+Extension.swift
  Carmu/Sources/Models/DayOfWeek.swift
  Carmu/Sources/Views/SessionStart/SessionStartView.swift
Labels: Feat

#364 [Feat] 셔틀 이름 "000000 셔틀"로 생성되도록 기능 변경
  Carmu.xcodeproj/project.pbxproj
  Carmu/Sources/Controllers/CrewMake/Driver/CrewNameSettingViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewInfoCheckViewController.swift
  Carmu/Sources/Controllers/MyPage/NameEditViewController.swift
  Carmu/Sources/Views/CrewMake/Driver/CrewNameSettingView.swift
  Carmu/Sources/Views/MyPage/NameEditView.swift
Labels: Feat

#366 [HOTFIX] ‼️초대코드 입력 시 크루 데이터 잘못 들어가는 문제
  Carmu/Sources/Controllers/CrewMake/Crew/BoardingPointSelectViewController.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Fix

#365 [Fix] 로그인, 회원탈퇴 시 제대로 처리되지 않는 문제 해결
  Carmu/Sources/Controllers/LoginViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
  Carmu/Sources/SceneDelegate.swift
  Carmu/Sources/Utils/FirebaseManager.swift
Labels: Fix, Refactor

#369 [Fix] 크루 편집 시 사용성 및 디자인 개선
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointViewController.swift
  Carmu/Sources/Controllers/MyPage/CrewEdit/CrewEditViewController.swift
  Carmu/Sources/Views/CrewMake/Driver/StopoverPointSelect/SelectDetailStopoverPointView.swift
Labels: Fix, Feat

#370 [Feat] 로그인/로그아웃/회원탈퇴 시 로딩 화면 표시
  Carmu/Sources/Controllers/CrewMake/Driver/StopoverPointCheckViewController.swift
  Carmu/Sources/Controllers/LoginViewController.swift
  Carmu/Sources/Controllers/MyPage/Settings/SettingsViewController.swift
  Carmu/Sources/Views/LoginView.swift
  Carmu/Sources/Views/MyPage/CrewInfo/CrewInfoDriverView.swift
  Carmu/Sources/Views/MyPage/Settings/SettingsView.swift
Labels: Feat

#374 [Feat] 문의하기 화면 앱스토어 리뷰 버튼 연결
  Carmu/Sources/Controllers/MyPage/Settings/InquiryViewController.swift
  Carmu/Sources/Extensions/Bundle+Extension.swift
Labels: Feat
