Repository DeveloperAcademy-POSTECH/MacC-Team-DGC, pull requests merged in 2023-09, with the labels that each got.

#4 Bazzi/feat/#2
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/SessionList/CustomListTableViewCell.swift
  Carmunication/Controllers/SessionList/GroupAddTableViewCell.swift
  Carmunication/Controllers/SessionList/GroupAddViewController.swift
  Carmunication/Controllers/SessionList/GroupDetailViewController.swift
  Carmunication/Controllers/SessionList/SelectPointMapViewController.swift
  Carmunication/Controllers/SessionListViewController.swift
Labels: Feat, Add, Chore, Refactor

#7 [feat] 애플 로그인 관련 세팅 및 구현
  .github/ISSUE_TEMPLATE/dgc-issue-template.md
  .github/pull_request_template.md
  .gitignore
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/AppDelegate.swift
  Carmunication/Carmunication.entitlements
  Carmunication/Controllers/LoginViewController.swift
  Carmunication/SceneDelegate.swift
Labels: Feat, Setting

#9 [Design] 세션 시작하기 레이아웃 설정
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/SessionStart/GroupCollectionViewCell.swift
  Carmunication/Controllers/SessionStart/ModalQueueViewController.swift
  Carmunication/Controllers/SessionStart/SessionMapViewController.swift
  Carmunication/Controllers/SessionStartViewController.swift
  Carmunication/Models/GroupData.swift
Labels: Design

#10 [Design] 로그인 화면 레이아웃 구성
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/LoginViewController.swift
  Carmunication/Controllers/MainTabBarViewController.swift
  Carmunication/Controllers/MyPage/MyPageViewController.swift
Labels: Design

#15 [Feat] 애플 로그인 - 로그아웃, 회원탈퇴 구현
  Carmunication.xcodeproj/project.pbxproj
  Carmunication/Controllers/LoginViewController.swift
  Carmunication/Controllers/MyPage/FriendListViewController.swift
  Carmunication/Controllers/MyPage/MyPageViewController.swift
  Carmunication/Controllers/MyPage/SettingsViewController.swift
Labels: Feat
